FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf

WORKDIR /api

ADD . /api

RUN apt-get -y update
RUN apt-get -y install python3.9
RUN apt-get -y install python3-pip

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

RUN python3 manage.py makemigrations
RUN python3 manage.py migrate

RUN chmod +x nginx_start.sh

ENTRYPOINT bash nginx_start.sh