version: '3.8'

services:
  webServer:
    image: nginx:latest
    container_name: webServer
    depends_on:
        - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - api

  api:
    image: drf-api
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
